[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# foundry.toml
allow_paths = ["src", "lib"]
 
solc_version = '0.8.26'
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true

# For FHE mock contract
isolate = true

[profile.default.optimizer_details]
# Enable Yul optimizer with stack optimization
yul = true